/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BuilderQuizRouteImport } from './routes/builder.quiz'
import { Route as BuilderMillionaireRouteImport } from './routes/builder.millionaire'
import { Route as BuilderJeopardyRouteImport } from './routes/builder.jeopardy'
import { Route as QuizGameIdResultsRouteImport } from './routes/quiz.$gameId.results'
import { Route as PlayQuizIdRouteImport } from './routes/play.quiz.$id'
import { Route as PlayMillionaireIdRouteImport } from './routes/play.millionaire.$id'
import { Route as PlayJeopardyIdRouteImport } from './routes/play.jeopardy.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuilderQuizRoute = BuilderQuizRouteImport.update({
  id: '/builder/quiz',
  path: '/builder/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const BuilderMillionaireRoute = BuilderMillionaireRouteImport.update({
  id: '/builder/millionaire',
  path: '/builder/millionaire',
  getParentRoute: () => rootRouteImport,
} as any)
const BuilderJeopardyRoute = BuilderJeopardyRouteImport.update({
  id: '/builder/jeopardy',
  path: '/builder/jeopardy',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizGameIdResultsRoute = QuizGameIdResultsRouteImport.update({
  id: '/quiz/$gameId/results',
  path: '/quiz/$gameId/results',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayQuizIdRoute = PlayQuizIdRouteImport.update({
  id: '/play/quiz/$id',
  path: '/play/quiz/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayMillionaireIdRoute = PlayMillionaireIdRouteImport.update({
  id: '/play/millionaire/$id',
  path: '/play/millionaire/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayJeopardyIdRoute = PlayJeopardyIdRouteImport.update({
  id: '/play/jeopardy/$id',
  path: '/play/jeopardy/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/builder/jeopardy': typeof BuilderJeopardyRoute
  '/builder/millionaire': typeof BuilderMillionaireRoute
  '/builder/quiz': typeof BuilderQuizRoute
  '/play/jeopardy/$id': typeof PlayJeopardyIdRoute
  '/play/millionaire/$id': typeof PlayMillionaireIdRoute
  '/play/quiz/$id': typeof PlayQuizIdRoute
  '/quiz/$gameId/results': typeof QuizGameIdResultsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/builder/jeopardy': typeof BuilderJeopardyRoute
  '/builder/millionaire': typeof BuilderMillionaireRoute
  '/builder/quiz': typeof BuilderQuizRoute
  '/play/jeopardy/$id': typeof PlayJeopardyIdRoute
  '/play/millionaire/$id': typeof PlayMillionaireIdRoute
  '/play/quiz/$id': typeof PlayQuizIdRoute
  '/quiz/$gameId/results': typeof QuizGameIdResultsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/builder/jeopardy': typeof BuilderJeopardyRoute
  '/builder/millionaire': typeof BuilderMillionaireRoute
  '/builder/quiz': typeof BuilderQuizRoute
  '/play/jeopardy/$id': typeof PlayJeopardyIdRoute
  '/play/millionaire/$id': typeof PlayMillionaireIdRoute
  '/play/quiz/$id': typeof PlayQuizIdRoute
  '/quiz/$gameId/results': typeof QuizGameIdResultsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/builder/jeopardy'
    | '/builder/millionaire'
    | '/builder/quiz'
    | '/play/jeopardy/$id'
    | '/play/millionaire/$id'
    | '/play/quiz/$id'
    | '/quiz/$gameId/results'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/builder/jeopardy'
    | '/builder/millionaire'
    | '/builder/quiz'
    | '/play/jeopardy/$id'
    | '/play/millionaire/$id'
    | '/play/quiz/$id'
    | '/quiz/$gameId/results'
  id:
    | '__root__'
    | '/'
    | '/builder/jeopardy'
    | '/builder/millionaire'
    | '/builder/quiz'
    | '/play/jeopardy/$id'
    | '/play/millionaire/$id'
    | '/play/quiz/$id'
    | '/quiz/$gameId/results'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuilderJeopardyRoute: typeof BuilderJeopardyRoute
  BuilderMillionaireRoute: typeof BuilderMillionaireRoute
  BuilderQuizRoute: typeof BuilderQuizRoute
  PlayJeopardyIdRoute: typeof PlayJeopardyIdRoute
  PlayMillionaireIdRoute: typeof PlayMillionaireIdRoute
  PlayQuizIdRoute: typeof PlayQuizIdRoute
  QuizGameIdResultsRoute: typeof QuizGameIdResultsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builder/quiz': {
      id: '/builder/quiz'
      path: '/builder/quiz'
      fullPath: '/builder/quiz'
      preLoaderRoute: typeof BuilderQuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builder/millionaire': {
      id: '/builder/millionaire'
      path: '/builder/millionaire'
      fullPath: '/builder/millionaire'
      preLoaderRoute: typeof BuilderMillionaireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builder/jeopardy': {
      id: '/builder/jeopardy'
      path: '/builder/jeopardy'
      fullPath: '/builder/jeopardy'
      preLoaderRoute: typeof BuilderJeopardyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/$gameId/results': {
      id: '/quiz/$gameId/results'
      path: '/quiz/$gameId/results'
      fullPath: '/quiz/$gameId/results'
      preLoaderRoute: typeof QuizGameIdResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/quiz/$id': {
      id: '/play/quiz/$id'
      path: '/play/quiz/$id'
      fullPath: '/play/quiz/$id'
      preLoaderRoute: typeof PlayQuizIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/millionaire/$id': {
      id: '/play/millionaire/$id'
      path: '/play/millionaire/$id'
      fullPath: '/play/millionaire/$id'
      preLoaderRoute: typeof PlayMillionaireIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/jeopardy/$id': {
      id: '/play/jeopardy/$id'
      path: '/play/jeopardy/$id'
      fullPath: '/play/jeopardy/$id'
      preLoaderRoute: typeof PlayJeopardyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuilderJeopardyRoute: BuilderJeopardyRoute,
  BuilderMillionaireRoute: BuilderMillionaireRoute,
  BuilderQuizRoute: BuilderQuizRoute,
  PlayJeopardyIdRoute: PlayJeopardyIdRoute,
  PlayMillionaireIdRoute: PlayMillionaireIdRoute,
  PlayQuizIdRoute: PlayQuizIdRoute,
  QuizGameIdResultsRoute: QuizGameIdResultsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
